# remap prefix from 'C-b' to 'C-x'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

bind 3 split-window -h
bind 2 split-window -v
bind k kill-pane

set-option -g default-command "/usr/bin/nu --experimental-options=native-clip"

set-option -sa terminal-overrides ',xterm-256color:RGB'
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status-bg "#3b4252"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "nordtheme/tmux"

run '~/.tmux/plugins/tpm/tpm'
